carshareadm/carshare

client/modules/Layout/Layout.js
client/modules/Layout/components/UserBar/UserBar.js

Login frontend

---

client/main.css
client/modules/Locations/Locations.css
client/modules/Locations/Locations.js
client/modules/Locations/components/Cars/Cars.css
client/modules/Locations/components/Cars/Cars.js
client/modules/Locations/components/GoogleMap/GoogleMap.js
client/modules/Locations/components/GoogleMap/components/GMap.js
client/modules/Locations/components/GoogleMap/components/Marker.js
client/modules/Locations/components/SelectLocation/SelectLocation.css
client/modules/Locations/components/SelectLocation/SelectLocation.js
client/modules/Locations/distanceKM.js
package-lock.json
package.json
server/controllers/cars/cars.controller.js
server/dummyData.js

* Geolocation uses your location at page load
* Car data moved up to Location for maps to have access to it
* Markers on the map
* Initial coordinates Australia and current after
* Cars are sorted based on distance from current
* Markers turned on again
* Use car locations for search
* Set Initial Location button works
* Styling
* Code Cleanup

Locations02 (#63)

---

client/modules/Booking/Booking.js
client/modules/Cars/Cars.css
client/modules/Cars/Cars.js
client/modules/Layout/components/Header/Header.js
client/modules/Locations/components/Cars/Cars.js
client/routes.js

GOT it working and figured out the param for booking. XD
Updated booking link to provide carid to the booking page.
Booking page now shows info based on param  - carid

Working cars and booking page front end

---

client/modules/Layout/Layout.css
client/modules/Layout/Layout.js
client/modules/Layout/components/Footer/Footer.css

This is the update tot the CSS footer.  Most notably in Layout.js, the footer was moved under the body content to align the footer as high as possible

Updating CSS for footer

---

client/modules/PaymentDetails/PaymentDetails.js

replaced Array.from() in PaymentDetails.js

---

server/__tests__/controllers/car.controller.js
server/controllers/cars/cars.controller.js
server/routes/cars.routes.js

Return cars based on type

---

client/modules/Layout/components/Header/Header.js
client/modules/Layout/components/UserBar/UserBar.css
client/modules/Layout/components/UserBar/UserBar.js
client/modules/Login/Login.css
client/modules/Login/Login.js
client/modules/Registration/Registration.css
client/modules/Registration/Registration.js
client/routes.js
package.json

User bar update. Front end login and registration finalisation and bootstrap.
Updated UserBar login presentation.
update test command

Registration updated to follow design

---

client/modules/Layout/Layout.js

Testing update of burger menu over userbar

Testing update of menu

---

client/modules/Layout/components/UserBar/UserBar.js

because this was missing and the app server bundle incorrporates the client code, the app broke completely >.<

require redirect in userbar

---

client/modules/Faq/Faq.css
client/modules/Faq/Faq.js

Update to the FAQ CSS and JS Static page

Update CSS for static pages

---

client/modules/Home/Home.css
client/modules/Layout/components/UserBar/UserBar.css

Updates to the CSS for the home page and the login bar.

CSS updates for home page and login bar

---

client/modules/Confirmation/Confirmation.js
client/modules/Profile/Profile.js
client/modules/Registration/Registration.js
client/services/confirm.service.js
package-lock.json
package.json
server/__tests__/controllers/account/login.controller.test.js
server/__tests__/controllers/account/register.controller.test.js
server/__tests__/controllers/car/car.controller.js
server/__tests__/controllers/confirm/confirm.controller.test.js
server/__tests__/controllers/confirm/email.controller.test.js
server/__tests__/controllers/confirm/sms.controller.test.js
server/__tests__/controllers/profile/profile.controller.test.js
server/config.js
server/controllers/confirm/email.controller.js
server/controllers/profile/profile.controller.js
server/middleware/__tests__/isAuthenticatedGuard.test.js
server/routes/confirm.routes.js
server/util/email.helper.js

reworking frontend profile confirmation with email sending
updated tests and profile backend

send email via sendgrid

---

client/modules/Contact/Contact.css
client/modules/Contact/Contact.js
client/modules/PaymentDetails/PaymentDetails.js
server/app.js
server/controllers/contact/contact.controller.js
server/models/enquiry.js
server/routes/contact.routes.js

Adds enquiries to database only.

send enquiry functionality

---

client/modules/History/History.css
client/modules/History/History.js
client/modules/History/components/HistoryItem.css
client/modules/History/components/HistoryItem.js
client/modules/Layout/components/UserBar/UserBar.js
client/routes.js
server/__tests__/controllers/account/profile.controller.test.js
server/__tests__/controllers/car/car.controller.test.js
server/controllers/profile/profile.controller.js
server/routes/profile.routes.js

History pages, backend and tests. Nothing to test on frontend as we don't have any bookings in dummy data.

History start

---

client/modules/Contact/Contact.js
server/controllers/contact/contact.controller.js
server/dummyData.js
server/models/enquiry.js

Added confirmationCodeType for dummy data user.

Added name field to enquiries.

---

.babelrc
package-lock.json
package.json
server/server.js

not sure why this is suddenly necessary :-(

added a babel package for build process

---

client/modules/Layout/components/Header/Header.js

Update logo in header with link to home

Logo link update

---

client/modules/Damages/Damages.css
client/modules/Damages/Damages.js
client/modules/History/components/HistoryItem.js
client/routes.js
server/__tests__/controllers/damage/damage.controller.test.js
server/app.js
server/controllers/damage/damage.controller.js
server/routes/damage.routes.js

Frontend start and backend tests for Damages. No Image upload yet. Bug fixed in History Item

Damage start

---

client/modules/FileUploader/FileUploader.js

Changes to file upload to inform user of image approval by admin

Update licence text on upload 2

---

client/modules/Damages/Damages.js
server/controllers/damage/damage.controller.js
server/controllers/images/upload.controller.js

Uploading an image and saving the damage report. Description will appear only if the image was uploaded. Small fix for logger

Upload damage img

---

client/modules/Booking/Booking.js
package-lock.json
package.json
server/__tests__/controllers/booking/booking.controller.test.js
server/controllers/account/register.controller.js
server/controllers/booking/booking.controller.js
server/dummyData.js

Updating booking creation process to include test. 
Controller test added. - Only working tests included, non functioning tests removed in this PR
bootstrap table package added in preparation to change booking timetable look

Booking controller update and test added

---

client/modules/FileUploader/FileUploader.js
client/modules/Profile/Profile.js

removed notice text from uploader js and added static text to the profile page

backout uploader changes

---

client/modules/Booking/Booking.js
server/__tests__/controllers/booking/booking.controller.test.js
server/controllers/booking/booking.controller.js
server/routes/booking.routes.js

checkBooking function removed as it will be redundant

Controller update, checkbooking function removed

---

client/modules/History/History.js
client/modules/History/components/HistoryItem.css
client/modules/History/components/HistoryItem.js
server/__tests__/controllers/damage/damage.controller.test.js
server/__tests__/controllers/profile/profile.controller.test.js
server/controllers/cars/cars.controller.js
server/controllers/damage/damage.controller.js
server/controllers/profile/profile.controller.js
server/dummyData.js
server/models/booking.js
server/models/car.js
server/models/damage.js
server/models/damageReport.js

The damages are not displayed yet, there's also no sorting by the date in historyItems, but the damage logging works for the current booking.

History checks

---

client/modules/Contact/Contact.css
client/modules/Contact/Contact.js
client/modules/PaymentDetails/PaymentDetails.js
server/controllers/paymentDetails/paymentDetails.controller.js
server/routes/paymentDetails.routes.js

Updated controller to use save to encrypt card num
and update last 4 digits.

Removed CVV input, improved interaction.

---

client/modules/Damages/Damages.js
client/modules/History/components/HistoryItem.js
server/__tests__/controllers/profile/profile.controller.test.js
server/controllers/damage/damage.controller.js
server/controllers/profile/profile.controller.js
server/models/booking.js
server/models/damage.js

Renamed DamageReport to Damage. Changed Damage model to keep the car and be retrieved either by car or booking (to use in admin functionality)

Damages pointer if car has damages

---

client/modules/Booking/Booking.js
server/controllers/booking/booking.controller.js

Booking controller alreadybooked flag to prevent issues with send after header is already sent error. 
Booking front end updated to provide alerts for issues.
Booking front end now includes dummy ccv check prior to booking confirmation. 
- New PR will move the final post behaviour to after the ccv is submitted.

Booking frontend updated

---

client/modules/About/About.css
client/modules/About/About.js

updated about page css and links

Update About CSS and links

---

client/modules/Booking/Booking.js
client/modules/Booking/components/TimeTable.js
server/controllers/cars/cars.controller.js

Fixed minor bugs, added weeks switching

Booking to history

---

client/modules/Booking/components/TimeTable.js
client/modules/Damages/Damages.js
server/__tests__/controllers/booking/booking.controller.test.js
server/controllers/booking/booking.controller.js
server/controllers/damage/damage.controller.js
server/models/booking.js
server/models/car.js
server/models/damage.js

i started to leave a comment about the booking query, then i got sucked into the rabbit hole of writing it in one mongoose statement... its simpler (in a more complicated kind of way >.<)

Booking model update, Controller updated to calc cost

---

client/modules/Damages/Damages.css
client/modules/Damages/Damages.js

Updates to CSS fro damage pages

CSS updates on Damages Pages

---

package.json

force node version

---

client/modules/Manage/Locations/LocationsAdm.js
client/modules/Manage/Locations/components/LocationAdm.js
client/services/manage.service.js
server/__tests__/controllers/manage/manage.locations.controller.test.js
server/controllers/manage/manage.locations.controller.js
server/routes/manage.routes.js

locations adm list and edit component

manage locations backend for update, plus tests

---

client/main.css
client/modules/Emergency/Emergency.css
client/modules/Emergency/Emergency.js
client/routes.js

A new emergency page with some CSS updates

added emergency page

---

client/modules/Cars/components/Car.js

PR to correct hourly rate not being displayed

Car pg price bug fx

---

client/modules/Layout/components/Header/Header.js
client/modules/Specials/Specials.css
client/modules/Specials/Specials.js

CSS updates to the special offers pages, as well as adding the Special offers and emergency contact pages to the main menu.

Updates to special offers page

---

client/main.css
client/modules/Contact/Contact.css
client/modules/Contact/Contact.js
client/modules/Specials/Specials.js

Updates to contact page styling and main css

updated main ccs and contacts page

---

client/main.css
client/modules/Contact/Contact.js
client/modules/Registration/Registration.css
client/modules/Registration/Registration.js

Updates to main CSS fro contacts and registration page

CSS updates to registration and contacts

---

client/modules/Damages/Damages.js
client/modules/FileUploader/FileUploader.js
client/modules/Manage/Cars/components/CarAdm.js
client/modules/Manage/Cars/components/CarImage.css
client/modules/Manage/Cars/components/CarImage.js
client/modules/Profile/Profile.js
client/services/file.service.js
client/services/manage.service.js
package.json
server/__tests__/controllers/damage/damage.controller.test.js
server/controllers/booking/booking.controller.js
server/controllers/cars/cars.controller.js
server/controllers/images/download.controller.js
server/controllers/images/upload.controller.js
server/controllers/manage/manage.cars.controller.js
server/models/car.js
server/models/image.js
server/routes/cars.routes.js
server/routes/manage.routes.js
server/util/aws.helper.js
webpack.config.babel.js

carimage component

---

client/modules/Booking/Booking.js
server/__tests__/controllers/offer/offer.controller.test.js
server/app.js
server/controllers/booking/booking.controller.js
server/controllers/offer/offer.controller.js
server/dummyData.js
server/routes/offer.routes.js

Booking Fend updated with calculate offer code.
Offer Bend and basic test implemented.

Booking Frontend updated. Offer Backend & basic test implemented

---

client/main.css
client/modules/Manage/Locations/LocationsAdm.js
client/modules/Manage/Locations/components/LocationAdm.css
client/modules/Manage/Locations/components/LocationAdm.js
client/modules/Manage/Locations/components/MapContainer.js
client/services/manage.service.js
server/__tests__/controllers/manage/manage.locations.controller.test.js
server/controllers/manage/manage.locations.controller.js
server/models/coordinate.js
server/routes/account.routes.js
server/routes/manage.routes.js

create a new location
added tests for Location POST

LocationAdm map with marker that updates on click

---

client/modules/History/History.js
client/modules/History/components/HistoryItem.js
server/__tests__/controllers/booking/booking.controller.test.js
server/controllers/booking/booking.controller.js
server/routes/booking.routes.js

Basic test for extension.
Cancellation backend added. - Only allowing for cancellation of future booking. 
Also, sorry about the autoFix in history.js - I hope it isn't too hard to follow

Booking Bend change, added cancellation and extension method. 

---

client/main.css
client/modules/Confirmation/Confirmation.js
client/modules/Contact/Contact.js
client/modules/Login/Login.css
client/modules/Login/Login.js
client/modules/Registration/Registration.css
client/modules/Registration/Registration.js

Updates to the buttons and styles on the login, contact, register, confirmation pages

Updates to CSS Main Login Confirmation Register Contact

---

client/modules/Cars/components/Car.js
client/modules/FileUploader/FileUploader.js
client/modules/Manage/Cars/CarsAdm.js
client/modules/Manage/Cars/components/CarAdm.js
client/modules/Manage/Locations/LocationsAdm.js
client/modules/Manage/Locations/components/LocationAdm.js
client/services/manage.service.js
server/__tests__/controllers/manage/manage.cars.controller.test.js
server/controllers/cars/cars.controller.js
server/controllers/manage/manage.cars.controller.js
server/models/image.js
server/routes/manage.routes.js

manage cars add new car with image

---

README.md
client/modules/Confirmation/Confirmation.js
client/modules/Profile/Profile.js
client/modules/Profile/components/DeleteProfile.js
client/modules/Profile/components/DeleteProfileForm.js
client/routes.js
server/__tests__/controllers/profile/profile.controller.test.js
server/controllers/profile/profile.controller.js
server/routes/profile.routes.js

backend delete profile endpoint and test

---

server/app.html.js

1 liner for meta so I can test google search on out website

google-site-verification meta tag

---

client/main.css
client/modules/History/History.js
client/modules/History/components/HistoryItem.css
client/modules/History/components/HistoryItem.js

Updates to main css and bookings/history pages

CSS updates to bookings

---

client/main.css
client/modules/Layout/components/Header/Header.js
client/modules/Layout/components/UserBar/UserBar.js

Removed unused search from the userbar

Userbar fix

---

client/main.css
client/modules/About/About.js
client/modules/Damages/Damage.js
client/modules/Damages/Damages.css
client/modules/Damages/Damages.js
client/modules/Emergency/Emergency.js
client/modules/Faq/Faq.css
client/modules/Faq/Faq.js
client/modules/Locations/Locations.css
client/modules/Locations/components/SelectLocation/SelectLocation.css
client/modules/Login/Login.js
client/modules/Profile/Profile.css
client/modules/TermsAndConditions/TermsAndConditions.js

CSS Updates to static pages and damages

updates to css pages

---

client/modules/Layout/components/UserBar/UserBar.js
client/modules/Login/Login.js
client/modules/Profile/components/DeleteProfile.js

fixes https://trello.com/c/tQDjPyM3 and https://trello.com/c/oziSxqke

login feedback, delete account feedback

---

client/modules/Damages/Damages.js
client/modules/Manage/Damages/DamagesAdm.js
client/modules/Manage/Locations/LocationsAdm.js
client/modules/Manage/Manage.js
client/modules/Manage/Statistics/StatBlock.css
client/modules/Manage/Statistics/StatBlock.js
client/services/manage.service.js
server/controllers/manage/manage.bookings.controller.js
server/controllers/manage/manage.cars.controller.js
server/controllers/manage/manage.damages.controller.js
server/controllers/manage/manage.enquiries.controller.js
server/controllers/manage/manage.locations.controller.js
server/controllers/manage/manage.users.controller.js
server/models/enquiry.js
server/routes/manage.routes.js

cars stats
damages stats
locations stats
users and enquiries stats

bookings stats

---

client/main.css
client/modules/Damages/Damages.js
client/modules/History/components/HistoryItem.js
client/modules/Layout/components/UserBar/UserBar.js

updated history links to bookings
updated damages button and some formating

fix bugs in bookings

---

client/modules/Manage/Enquiries/EnquiriesAdm.js
server/controllers/manage/manage.enquiries.controller.js

Simple change to display the enquiries from latest first.
Also added line of description what the page does.

reverse enquiries order

---

client/main.css
client/modules/Booking/Extension.css
client/modules/Booking/Extension.js

Update Styling for extend bookings

Extend bookings CSS updates

---

client/modules/Faq/components/Search.css
client/modules/Faq/components/Search.js

Search styling update

---

client/modules/Profile/Profile.js
server/controllers/profile/profile.controller.js

Populate profile address fields.
Add missing onBlur attribute to street2 field.

Bug begone.

---

server/__tests__/controllers/contact/contact.controller.test.js
server/__tests__/controllers/manage/manage.enquiries.controller.test.js
server/__tests__/controllers/paymentDetails/paymentDetails.controller.test.js
server/controllers/contact/contact.controller.js
server/controllers/paymentDetails/paymentDetails.controller.js

These are my last commits, hopefully, before the submission.

payment details and contact controller tests

---

server/dummyData.js

Updates value for location to rectify issue.

Correcting incorrect behaviour from new cars added
